spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: ${USER_NAME}
      password: ${USER_PASSWORD}