spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/planes
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          scheduler:
            instanceName: integration
            instanceId: AUTO
            skipUpdateCheck: true
            batchTriggerAcquisitionMaxCount: 20
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            tablePrefix: qtz_
            isClustered: true
            acquireTriggersWithinLock: true
            useProperties: true